---
openapi: "3.0.0"
info:
  title: "DOC-PIPE API"
  #  description: "API endpoints for DOC-PIPE"
  #  contact:
  #    name: "Вячеслав Макаров"
  #    email: "vvmakarov@corp.finam.ru"
  #    url: "https://git.finam.ru/projects/AIDEV/repos/doc-pipe"
  #
  #    swagger.io: https://swagger.io/docs/specification/
  version: "0.0.91"
servers:
  - url: "https://doc-pipe-dev.finam.ru"
    description: "DEV server"
  - url: "https://doc-pipe.finam.ru"
    description: "PROD server"
  - url: "http://localhost:8866/"
    description: "Local server"

security:
  - Token: []

paths:
  /api/v1/health:
    get:
      tags: ["DOC-PIPE-API"]
      summary: "Health Check"
      description: "Проверка работоспособности сервера, предоставляющего API"
      responses:
        200:
          description: "Сервис жив"
        default:
          description: "Сервис не здоров"
      security: []

  /health:
    $ref: "#/paths/~1api~1v1~1health"

  /api/v1/doc-pipe/clean:
    post:
      tags: ["DOC-PIPE-API"]
      summary: "Очистка ошибок страниц"
      description: "Очистка ошибок для переданных страниц чтобы вернуть их в обход"
      requestBody:
        description: "Передаваемые параметры"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pagesIds:
                  type: array
                  items: integer
                blockId:
                  type: integer
      responses:
        200:
          description: "Ошибки успешно очищены"
          content:
            text/plain:
              schema:
                type: string
                example: success
        422:
          description: "Ошибка в параметрах body"
          content:
            text/plain:
              schema:
                type: string
                example: Unprocessable Entity
        default:
          description: "Внутрення ошибка сервера"

  /api/v1/doc-pipe/crawl:
    post:
      tags: ["DOC-PIPE-API"]
      summary: "Запуск обхода страниц"
      description: "Обход страниц по перееданным параметрам, testMode позволяет автоматически очистить все ошибки переданных страниц перед запуском"
      requestBody:
        description: "Передаваемые параметры"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                crawlType: 
                  type: all, bulk
                pagesIds:
                  type: array
                  items: integer
                blockId:
                  type: integer
                testMode:
                  type: boolean
      responses:
        200:
          description: "Ошибки успешно очищены"
          content:
            text/plain:
              schema:
                type: string
                example: success
        422:
          description: "Ошибка в параметрах body"
          content:
            text/plain:
              schema:
                type: string
                example: Unprocessable Entity
        default:
          description: "Внутрення ошибка сервера"

components:
  securitySchemes:
    Token:
      type: http
      scheme: bearer
      bearerFormat: string
      description: |
        **Сеансовый токен или постоянный серверный токен**.  
        Тестовый токен можно запросить у Макарова Вячеслава.

  schemas:

  parameters:
    ContentTypeJSONParam:
      in: header
      name: Content-Type
      schema:
        type: string
        enum:
          - application/json
      required: true

  responses:
    MissingAuthHeader:
      description: Missing authorization header
      content:
        text/plain:
          schema:
            type: string
            example: Missing authorization header

    Unauthorized:
      description: Unauthorized
      content:
        text/plain:
          schema:
            type: string
            example: Unauthorized

tags:
  - name: "DOC-PIPE-API"
