export interface ICoreDlinkRecord {
  linkId?: number,
  blockId: number,
  url: string,
  use?: boolean | null,
  isDownload?: boolean | null,
  type?: string | null,
  content?: string | null,
  fileName?: string | null,
  js?: string | null,
  contentSelector?: string | null,
  parsePicture?: boolean | null,
  parsedText?: string | null,
  deleted?: boolean | null,
  httpCode?: number | null,
  crawlError?: string | null,
  useProxy?: boolean | null,
  note?: string | null,
  createdAt?: string | Date | number,
  createdBy: string,
  updatedAt?: string | Date | number,
  updatedBy: string,
}
